name = "regional-sale-ext"
type = "product_discounts"
api_version = "2023-01"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/regional-sale-ext.wasm"

[ui.paths]
create = "/regional-sale-ext/new"
details = "/regional-sale-ext/:id"
